defaults:
  - hydra: default
  - deepspeed@ds_cfg: train_hybrid_engine_zero1_optim_offload
#  - deepspeed@ds_cfg: train_hybrid_engine_zero2_optim_offload
  - _self_  # see here for more details: https://hydra.cc/docs/tutorials/basic/your_first_app/defaults/#composition-order-of-primary-config

hydra:
  searchpath:
    - file://conf/

data_dir: experiments/llama2.7b.chat.logiqav2.gpt35turbo-dpo-sft.H100.w2.v2.0/checkpoint-1600
train_file: ${data_dir}/logiqav2-train.full.qa.react.v1.0.1shot.sample20.clean_nodes.cluster.t0.95.TO.len2.in4.v0.1.full_only.sub_train.json
dev_file: ${data_dir}/logiqav2-train.full.qa.react.v1.0.1shot.sample20.clean_nodes.cluster.t0.95.TO.len2.in4.v0.1.full_only.sub_dev.json
test_file:

torch_dtype:
  _target_: general_util.training_utils.return_torch_dtype
  dtype: bfloat16

tokenizer_init:
  _target_: general_util.tokenization_utils.init_tokenizer
  tokenizer_path: ${model_name_or_path}
  padding_side: left

device_map:
  _target_: models.llama.return_single_device_map

model:
  _target_: models.llama.LlamaForCausalLMDPO.from_pretrained_with_ref_model
  beta: 0.1
  gradient_checkpointing: True
  pad_token_id: 0
  use_flash_attention_2: True
  torch_dtype: ${torch_dtype}
  device_map: ${device_map}
  ref_model:
    _target_: transformers.models.llama.LlamaForCausalLM.from_pretrained
    pretrained_model_name_or_path: ${model_name_or_path}
    torch_dtype: ${torch_dtype}
    use_flash_attention_2: True
    pad_token_id: 0
    device_map: ${device_map}
    # load_in_8bit: True  # 8-bit cannot use on H100


# Data loading
read_tensor:
  _target_: data.dpo.DPOMergeDataset
  original_data_file: ../research.data/LogiQA2.0/logiqa/DATA/LOGIQA/train.txt
  original_reader:
    _target_: data.logiqav2.LogicQAReader
    flat_options: True
  instruction:
    _target_: data.prompts.logiqav2.react.prompts.get_prompt
    prompt_name: react_v2
  template: "Context:\n{}\n\nQuestion:\n{}\n\nOptions:\n{}\n\n"
  compose_keys: [ "context", "question", "option_list" ]
  format_filter:
    _target_: data.dpo.ReActFormat


dist_load_data_barrier: False

extended_vocab:

# Data collator
collator:
  _target_: data.dpo.DPOCollator
  tokenizer: ${tokenizer_init}
  max_seq_length: 2048

# Dataloader
num_workers: 8
prefetch_factor: 2

# Wiki path pretrain v8.2
model_name_or_path: experiments/llama2.7b.chat.logiqav2.gpt35turbo-dpo-sft.H100.w2.v2.0/checkpoint-1600
pretrain:

exp_name: llama2.7b.chat.logiqav2.dpo.H100.w2.v4.0
exp_notes:
output_dir: experiments/${exp_name}


do_train: True
evaluate_during_training: True

do_eval: False
eval_sub_path: checkpoint-100

# Training hyper-parameters
per_gpu_train_batch_size: 2
per_gpu_eval_batch_size: 4
#learning_rate: 1e-4
#learning_rate: 5e-6
learning_rate: 1e-6
gradient_accumulation_steps: 6
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
#adam_betas: "(0.9, 0.999)"
#max_grad_norm: 0.0
total_dataset_len: -1
max_grad_norm: 1.0
num_train_epochs: 1
max_steps: 0
warmup_proportion: 0.01
warmup_steps: 0

# Optimizer
optimizer:
use_nvlamb:
bit_training:

logging_steps: 5
save_steps: 400
save_best: False
eval_steps: 400
ddp_eval: True
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1
fp16_bfloat16: True

# Prediction config
prediction_cfg:
  metric: "loss"
  measure: -1
  best_checkpoint:
  best_result:
eval_forward_fn:
  _target_: general_util.evaluator.DefaultForwardFn
post_process:
  _target_: post_processors.dpo.DPOEvalPostProcessor

ds_cfg:
  train_micro_batch_size_per_gpu: ${per_gpu_train_batch_size}
  gradient_accumulation_steps: ${gradient_accumulation_steps}
  optimizer:
    type: AdamW
    params:
      lr: ${learning_rate}
      betas: [ 0.9, 0.95 ]
      weight_decay: ${weight_decay}



summary_helper:
  _target_: general_util.tensorboard_helper.WandbWriter
  batch_index_or_keys:
  #    "train/pair_value_num": pair_value_num
  outputs_index_or_keys:
    "train/chosen_reward": chosen_reward
    "train/rejected_reward": rejected_reward

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
