defaults:
  - hydra: default
  - deepspeed@ds_cfg: train_hybrid_engine_zero1_optim_offload
#  - deepspeed@ds_cfg: train_hybrid_engine_zero2
  - _self_  # see here for more details: https://hydra.cc/docs/tutorials/basic/your_first_app/defaults/#composition-order-of-primary-config

hydra:
  searchpath:
    - file://conf/


train_file: ../merit-v2/openai-api-output/logiqav2-train-v1.1.full.qa.decompose.llama2.7b.chat.distil.dpo.10.fix.json
dev_file: ../merit-v2/openai-api-output/logiqav2-dev-v1.1.full.qa.decompose.llama2.7b.chat.distil.dpo.10.fix.json
test_file:

torch_dtype:
  _target_: general_util.training_utils.return_torch_dtype
  dtype: bfloat16

tokenizer_init:
  _target_: general_util.tokenization_utils.init_tokenizer
  tokenizer_path: ${model_name_or_path}
  padding_side: left

model:
  _target_: models.llama.LlamaForCausalLM.from_pretrained
  gradient_checkpointing: True
  pad_token_id: 0
  use_flash_attention_2: True
  torch_dtype: ${torch_dtype}


# Data loading
read_tensor_train:
  _target_: data.dpo.DPOMergeDataset
  original_data_file: ../research.data/LogiQA2.0/logiqa/DATA/LOGIQA/train.txt
  original_reader:
    _target_: data.logiqav2.LogicQAReader
    flat_options: True
  template: "[Context]\n{}\n\n[Question]\n{}\n\n[Options]\n{}\n\nPlease decompose the problem above into smaller ones so that we can solve it separately and reach the final answer by considering each subproblem and merge the sub-conclusions.\n\n"
  compose_keys: [ "context", "question", "option_list" ]

read_tensor_dev:
  _target_: data.dpo.DPOMergeDataset
  original_data_file: ../research.data/LogiQA2.0/logiqa/DATA/LOGIQA/dev.txt
  original_reader:
    _target_: data.logiqav2.LogicQAReader
    flat_options: True
  template: "[Context]\n{}\n\n[Question]\n{}\n\n[Options]\n{}\n\nPlease decompose the problem above into smaller ones so that we can solve it separately and reach the final answer by considering each subproblem and merge the sub-conclusions.\n\n"
  compose_keys: [ "context", "question", "option_list" ]

dist_load_data_barrier: False

extended_vocab:

# Data collator
collator:
  _target_: data.dpo.DPODataSFTCollator
  tokenizer: ${tokenizer_init}
  max_seq_length: 2048

# Dataloader
num_workers: 8
prefetch_factor: 2

# Wiki path pretrain v8.2
model_name_or_path: ../merit-v2/experiments/llama2.7b.chat.70b-chat-distil.logiqav2.A100.w2.v1.0/checkpoint-500/
pretrain:
resume: experiments/llama2.7b.chat.70b-chat-distil.logiqav2.dpo-sft.A100.w3.v1.0/checkpoint-800

exp_name: llama2.7b.chat.70b-chat-distil.logiqav2.dpo-sft.A100.w3.v1.0
exp_notes:
output_dir: experiments/${exp_name}  # Fix <pad token id>


do_train: True
evaluate_during_training: True

do_eval: True
eval_sub_path: checkpoint-100

# Training hyper-parameters
per_gpu_train_batch_size: 8
per_gpu_eval_batch_size: 16
#learning_rate: 1e-4
#learning_rate: 5e-6
learning_rate: 1e-6
gradient_accumulation_steps: 1
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
#adam_betas: "(0.9, 0.999)"
#max_grad_norm: 0.0
total_dataset_len: -1
max_grad_norm: 1.0
num_train_epochs: 5
max_steps: 0
warmup_proportion: 0.01
warmup_steps: 0

# Optimizer
optimizer:
use_nvlamb:
bit_training:

logging_steps: 5
save_steps: 200
save_best: False
eval_steps: 200
ddp_eval: True
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1
fp16_bfloat16: True

# Prediction config
prediction_cfg:
  metric: "loss"
  measure: -1
  best_checkpoint:
  best_result:
eval_forward_fn:
  _target_: general_util.evaluator.DefaultForwardFn
post_process:
  _target_: post_processors.dist_mixin.SFTLossOnlyPostProcessor

ds_cfg:
  train_micro_batch_size_per_gpu: ${per_gpu_train_batch_size}
  gradient_accumulation_steps: ${gradient_accumulation_steps}
  optimizer:
    type: AdamW
    params:
      lr: ${learning_rate}
      betas: [ 0.9, 0.95 ]
      weight_decay: ${weight_decay}



summary_helper:
  _target_: general_util.tensorboard_helper.WandbWriter
  batch_index_or_keys:
  outputs_index_or_keys:

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
