defaults:
  - hydra: default
  - post_process: gsm8k
  - api/vllm/vllm_params@sampling_params: sampling_param_greedy
  - _self_

hydra:
  searchpath:
    - file://conf/

train_file:
dev_file:
test_file: ../research.data/MetaMathQA/test/GSM8K_test.json

save_best: False
exp_name:
exp_notes:
output_dir: experiments/${exp_name}

step: 800
eval_sub_path: checkpoint-${step}

read_tensor:
  _target_: data.logic_combine.ResponseAlignDataset
  aligner:
    _target_: data.math.gsm8k_gold_answer_extractor
  template: "### Instruction:\n{query}\n\n### Response: Let's think step by step."
  instruction: "Below is an instruction that describes a task. Write a response that appropriately completes the request."
  max_data_num: -1
  service_based: False
  api_based: False
  index_field: "index"

sampling_params:
  stop: [ "<eos>", "\n\n\n\n", "### Instruction" ]

output_file: ${output_dir}/${eval_sub_path}/gsm8k.test.v1.0.0shot.json
flush_file: ${output_file}l

# Dataloader
num_workers: 48
prefetch_factor: 2

post_process:
  resume: False
  index_field: "index"
  label_field: "label"

ddp_eval: False
no_cuda: False
seed: 42
local_rank: -1

# Temporary variables
fp16: True
fp16_bfloat16: True
n_gpu: 1
device:
train_batch_size:
eval_batch_size:
world_size:
