defaults:
  - hydra: default
  - post_process: math
  - api/vllm/vllm_params@sampling_params: sampling_param_greedy
  - _self_

hydra:
  searchpath:
    - file://conf/

train_file:
dev_file:
test_file: ../research.data/MetaMathQA/test/MATH_test.json

save_best: False
exp_name:
exp_notes:
output_dir: experiments/${exp_name}

step: 800
eval_sub_path: checkpoint-${step}

read_tensor:
  _target_: data.logic_combine.ResponseAlignDataset
  aligner:
    _target_: data.math.math_gold_answer_extractor
    kv_mapping:
      instruction: query
  template: "{instruction}\n\n### Question: {query}\n\nSubQuestion 1: "
  instruction: "Given a question, please decompose it into sub-questions. For each sub-question, please answer it in a complete sentence, ending with \"The answer is\". When the original question is answerable, please start the sub-question with \"Now we can answer the question: \"."
  max_data_num: -1
  service_based: False
  api_based: False
  index_field: "idx"

sampling_params:
  stop: [ "<eos>", "\n\n\n\n", "### Instruction" ]

output_file: ${output_dir}/${eval_sub_path}/math.test.v1.1.0shot.json
flush_file: ${output_file}l

# Dataloader
num_workers: 48
prefetch_factor: 2

post_process:
  answer_clean:
    _target_: data.math.math_answer_cleaner
    separator: "The answer is"
  resume: False
  index_field: "idx"
  label_field: "label"

ddp_eval: False
no_cuda: False
seed: 42
local_rank: -1

# Temporary variables
fp16: True
fp16_bfloat16: True
n_gpu: 1
device:
train_batch_size:
eval_batch_size:
world_size:
