defaults:
  - hydra: default
#    - deepspeed@ds_cfg: train_hybrid_engine_zero1_optim_offload_lr  # Zero-1 w/ Optimizer offlad works on 4*A40 with 140 hours per epoch.  224GB CPU memory
  #  - deepspeed@ds_cfg: train_hybrid_engine_zero2_optim_offload
#  - deepspeed@ds_cfg: train_hybrid_engine_zero2
  - deepspeed@ds_cfg: train_hybrid_engine_zero1
#  - deepspeed@ds_cfg: train_hybrid_engine_zero1_lr
  #  - deepspeed@ds_cfg: train_hybrid_engine_zero3  # Zero-3 works on 4*A40 300 hours per epoch
  - _self_  # see here for more details: https://hydra.cc/docs/tutorials/basic/your_first_app/defaults/#composition-order-of-primary-config

hydra:
  searchpath:
    - file://conf/

sft_model_dir: experiments/llama2.7b.chat.logiqav2.llama-2-70b-chat.dpo-sft.A6K.w4.v1.0/checkpoint-1600/
fix_hack_data_dir: ${sft_model_dir}/fix_hack_data_dir/
attempt_response_file: ${sft_model_dir}/react-inter-states/process-rm/logiqav2-train.qa.react.v1.0.0shot.sample10.inter_ver2.0.rs0.2.r0.3.sample3.json
inter_states_file_train: ${sft_model_dir}/react-inter-states/logiqav2-train.full.qa.react.v1.0.0shot.sample10.clean_inter_ver2.0.rs0.2.r0.3.[1-2]-of-20.json
inter_states_file_dev: ${sft_model_dir}/react-inter-states/logiqav2-train.full.qa.react.v1.0.0shot.sample10.clean_inter_ver2.0.rs0.2.r0.3.0-of-20.json

train_file: ${attempt_response_file}
dev_file: ${attempt_response_file}
#test_file: ${sft_model_dir}/react-inter-states/logiqav2-train.full.qa.react.v1.0.0shot.sample10.clean_inter_ver2.0.rs0.2.r0.3.*-of-20.json
test_file: experiments/llama2.7b.chat.logiqav2.70b-distil.step.dpo.fix_hack.H100.w4.v1.0.s44/checkpoint-1200/logiqav2.react.train.0shot.sample5.v1.0.cleaned.json

torch_dtype:
  _target_: general_util.training_utils.return_torch_dtype
  dtype: bfloat16

tokenizer_init:
  _target_: general_util.tokenization_utils.init_tokenizer
  tokenizer_path: ${model_name_or_path}
  padding_side: left

device_map:
  _target_: models.llama.return_single_device_map

model:
  _target_: models.llama.LlamaModelForSequenceClassificationForEval.from_pretrained
  num_labels: 4
  gradient_checkpointing: True
  pad_token_id: 0
  attn_implementation: "flash_attention_2"
  torch_dtype: ${torch_dtype}
  device_map: ${device_map}


# Data loading
read_tensor_train:
  _target_: data.general.Attempt2ValueRewardModelingDataset
  max_value: 3
  original_data_file: ../research.data/LogiQA2.0/logiqa/DATA/LOGIQA/train.txt
  original_reader:
    _target_: data.logiqav2.LogicQAReader
    flat_options: True
  instruction:
    _target_: data.prompts.logiqav2.react.prompts.get_prompt
    prompt_name: react_v2
  reader:
    _target_: data.general.PartialTrajAttemptsReader
    partial_traj_file: ${inter_states_file_train}
  template: "Context:\n{}\n\nQuestion:\n{}\n\nOptions:\n{}\n\nThought 1: "
  compose_keys: [ "context", "question", "option_list" ]


read_tensor:
  _target_: data.general.Attempt2ValueRewardModelingDataset
  max_value: 3
  original_data_file: ../research.data/LogiQA2.0/logiqa/DATA/LOGIQA/train.txt
  original_reader:
    _target_: data.logiqav2.LogicQAReader
    flat_options: True
  instruction:
    _target_: data.prompts.logiqav2.react.prompts.get_prompt
    prompt_name: react_v2
  reader:
    _target_: data.general.PartialTrajAttemptsReader
    partial_traj_file: ${inter_states_file_dev}
  template: "Context:\n{}\n\nQuestion:\n{}\n\nOptions:\n{}\n\nThought 1: "
  compose_keys: [ "context", "question", "option_list" ]

read_tensor_test:
  _target_: data.general.CompleteTrajRewardModelingDataset
  original_data_file: ../research.data/LogiQA2.0/logiqa/DATA/LOGIQA/train.txt
  original_reader:
    _target_: data.logiqav2.LogicQAReader
    flat_options: True
  instruction:
    _target_: data.prompts.logiqav2.react.prompts.get_prompt
    prompt_name: react_v2
  reader:
    _target_: data.dpo.DPOPairReader
  template: "Context:\n{}\n\nQuestion:\n{}\n\nOptions:\n{}\n\nThought 1: "
  compose_keys: [ "context", "question", "option_list" ]


dist_load_data_barrier: False

extended_vocab:

# Data collator
collator:
  _target_: data.general.CompleteTrajStepRewardCollator
  tokenizer: ${tokenizer_init}
  max_seq_length: 4096

# Dataloader
num_workers: 8
prefetch_factor: 2

# Wiki path pretrain v8.2
model_name_or_path: ${sft_model_dir}
pretrain:
resume:

exp_name: llama2.7b.chat.logiqav2.70b-distil.prm.fix_hack.A100.w4.v1.2.s${seed}
exp_notes:
output_dir: experiments/${exp_name}


do_train: False
evaluate_during_training: True

do_eval: True
eval_sub_path: checkpoint-*

# Training hyper-parameters
per_gpu_train_batch_size: 4
per_gpu_eval_batch_size: 8
#learning_rate: 1e-4
#learning_rate: 5e-6
learning_rate: 1e-6
gradient_accumulation_steps: 4
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
#adam_betas: "(0.9, 0.999)"
#max_grad_norm: 0.0
total_dataset_len: -1
max_grad_norm: 1.0
num_train_epochs: 2
max_steps: 0
warmup_proportion: 0
warmup_steps: 200

# Optimizer
optimizer:
use_nvlamb:
bit_training:

logging_steps: 5
save_ds_state: False
save_steps: 200
save_best: False
eval_steps: 200
ddp_eval: True
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1
fp16_bfloat16: True

# Prediction config
prediction_cfg:
  metric: "acc"
  measure: 1
  best_checkpoint:
  best_result:
eval_forward_fn:
  _target_: general_util.evaluator.DefaultForwardFn
post_process:
  _target_: post_processors.dpo.ResponseProcessRewardPostProcessor
predict_dir: ${output_dir}/llama2.7b.chat.logiqav2.70b-distil.step.dpo.fix_hack.H100.w4.v1.0.s44.checkpoint-1200.logiqav2.react.train.0shot.sample5.v1.0.cleaned.v1.0

ds_cfg:
  train_micro_batch_size_per_gpu: ${per_gpu_train_batch_size}
  gradient_accumulation_steps: ${gradient_accumulation_steps}
  optimizer:
    type: AdamW
    params:
      lr: ${learning_rate}
      betas: [ 0.9, 0.95 ]
      weight_decay: ${weight_decay}


summary_helper:
  _target_: general_util.tensorboard_helper.WandbWriter
  batch_index_or_keys:
  #    "train/pair_value_num": pair_value_num
  outputs_index_or_keys:
#    "train/chosen_reward": chosen_reward
#    "train/rejected_reward": rejected_reward

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
