defaults:
  - hydra: default
#  - deepspeed@ds_cfg: train_hybrid_engine_zero1
  - deepspeed@ds_cfg: train_hybrid_engine_zero1_optim_offload_lr
#  - deepspeed@ds_cfg: train_hybrid_engine_zero2
  - _self_  # see here for more details: https://hydra.cc/docs/tutorials/basic/your_first_app/defaults/#composition-order-of-primary-config

hydra:
  searchpath:
    - file://conf/

sft_model_dir: experiments/llama2.7b.chat.reclor.gpt35turbo1106.dpo-sft.A100.w2.v1.0/checkpoint-2400
train_file: ${sft_model_dir}/reclor.react.train.0shot.sample10.tem0.7.v1.0.prm_v13_400_best_of_10.neg10.pos0.3.v2.2.(1,2,3).pair.min.pos_only.json
dev_file:
test_file:

torch_dtype:
  _target_: general_util.training_utils.return_torch_dtype
  dtype: bfloat16

tokenizer_init:
  _target_: general_util.tokenization_utils.init_tokenizer
  tokenizer_path: ${model_name_or_path}
  padding_side: left

device_map:
  _target_: models.llama.return_single_device_map

model:
  _target_: models.llama.LlamaForCausalLMDPO.from_pretrained_with_ref_model
  beta: 0.1
  gradient_checkpointing: True
  pad_token_id: 0
  attn_implementation: "flash_attention_2"
  torch_dtype: ${torch_dtype}
  device_map: ${device_map}
  ref_model:
    _target_: transformers.models.llama.LlamaForCausalLM.from_pretrained
    pretrained_model_name_or_path: ${model_name_or_path}
    torch_dtype: ${torch_dtype}
    attn_implementation: "flash_attention_2"
    pad_token_id: 0
    device_map: ${device_map}
#    load_in_8bit: True  # 8-bit cannot use on H100


# Data loading
read_tensor:
  _target_: data.dpo.DPOMergeDataset
  original_data_file: ../research.data/reclor_data/train.json
  original_reader:
    _target_: data.reclor.ReClorReader
    flat_options: True
  instruction:
    _target_: data.prompts.logiqav2.react.prompts.get_prompt
    prompt_name: react_v2
  template: "Context:\n{}\n\nQuestion:\n{}\n\nOptions:\n{}\n\nThought 1: "
  compose_keys: [ "context", "question", "option_list" ]

dist_load_data_barrier: False

extended_vocab:

# Data collator
collator:
  _target_: data.dpo.DPOCollator
  tokenizer: ${tokenizer_init}
  max_seq_length: 2048

# Dataloader
num_workers: 8
prefetch_factor: 2

# Wiki path pretrain v8.2
#model_name_or_path: ${sft_model_dir}
model_name_or_path: experiments/llama2.7b.chat.reclor.gpt351106.dpo.fix_hack.H100.w4.v1.0.s42/checkpoint-800
pretrain:


exp_name: llama2.7b.chat.reclor.gpt351106.step.dpo.fix_hack.A100.w2.v3.0.s${seed}
exp_notes:
output_dir: experiments/${exp_name}


do_train: True
evaluate_during_training: False

do_eval: False
eval_sub_path: checkpoint-100

# Training hyper-parameters
per_gpu_train_batch_size: 4  # H100
per_gpu_eval_batch_size: 4
#learning_rate: 1e-4
learning_rate: 5e-7
#learning_rate: 1e-6
gradient_accumulation_steps: 8
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
#adam_betas: "(0.9, 0.999)"
#max_grad_norm: 0.0
total_dataset_len: -1
max_grad_norm: 1.0
num_train_epochs: 2
max_steps: 0
warmup_proportion: 0
warmup_steps: 0

# Optimizer
optimizer:
use_nvlamb:
bit_training:

logging_steps: 5
save_ds_state: False
save_steps: 50
save_best: False
eval_steps: 50
ddp_eval: True
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1
fp16_bfloat16: True

# Prediction config
prediction_cfg:
  metric: "loss"
  measure: -1
  best_checkpoint:
  best_result:
eval_forward_fn:
  _target_: general_util.evaluator.DefaultForwardFn
post_process:
  _target_: post_processors.dpo.DPOEvalPostProcessor

ds_cfg:
  train_micro_batch_size_per_gpu: ${per_gpu_train_batch_size}
  gradient_accumulation_steps: ${gradient_accumulation_steps}
  optimizer:
    type: AdamW
    params:
      lr: ${learning_rate}
      betas: [ 0.9, 0.95 ]
      weight_decay: ${weight_decay}



summary_helper:
  _target_: general_util.tensorboard_helper.WandbWriter
  batch_index_or_keys:
  #    "train/pair_value_num": pair_value_num
  outputs_index_or_keys:
    "train/chosen_reward": chosen_reward
    "train/rejected_reward": rejected_reward

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
